---
- name: Copy VyOS scripts to VyOS system
  copy: src={{ item }} dest=/tmp/{{ item }} owner=root group=root mode=0744
  with_items:
    - vyos_end_session.sh
    - vyos_loadFile.sh
    - vyos_setup_session.sh
    - vyos_snippet.sh

- name: Copy VyOS configuration to VyOS system
  template: src={{ vyos_configuration }} dest=/tmp/configuration
  register: result

- name: Commit and save VyOS configuration
  command: /tmp/vyos_loadFile.sh /tmp/configuration chdir=/tmp
  when: result|changed
  environment:
    vyatta_prefix: "{{ vyos_prefix }}"
    vyatta_htmldir: "{{ vyos_prefix }}/share/html"
    vyatta_datadir: "{{ vyos_prefix }}/share"
    vyatta_op_templates: "{{ vyos_prefix }}/share/vyatta-op/templates"
    vyatta_sysconfdir: "{{ vyos_prefix }}/etc"
    vyatta_sharedstatedir: "{{ vyos_prefix }}/com"
    vyatta_sbindir: "{{ vyos_prefix }}/sbin"
    vyatta_cfg_templates: "{{ vyos_prefix }}/share/vyatta-cfg/templates"
    vyatta_CFG_GROUP_NAME: vyattacfg
    vyatta_bindir: "{{ vyos_prefix }}/bin"
    vyatta_USER_LEVEL_DIR: "{{ vyos_prefix }}/etc/shell/level/admin"
    vyatta_libdir: "{{ vyos_prefix }}/lib"
    vyatta_localstatedir: "{{ vyos_prefix }}/var"
    vyatta_libexecdir: "{{ vyos_prefix }}/libexec"
    vyatta_datarootdir: "{{ vyos_prefix }}/share"
    vyatta_configdir: "{{ vyos_prefix }}/config"
    vyatta_infodir: "{{ vyos_prefix }}/share/info"
    vyatta_localedir: "{{ vyos_prefix }}/share/locale"
